insert into CHILD (child_id, child_dob, child_name)
values (1, to_date('10-05-2018', 'dd-mm-yyyy'), 'John Smith');
insert into CHILD (child_id, child_dob, child_name)
values (2, to_date('20-08-2017', 'dd-mm-yyyy'), 'Emily Davis');
insert into CHILD (child_id, child_dob, child_name)
values (3, to_date('15-12-2016', 'dd-mm-yyyy'), 'Michael Johnson');
insert into CHILD (child_id, child_dob, child_name)
values (4, to_date('25-09-2015', 'dd-mm-yyyy'), 'Sarah Brown');
insert into CHILD (child_id, child_dob, child_name)
values (5, to_date('05-11-2014', 'dd-mm-yyyy'), 'David Wilson');
insert into CHILD (child_id, child_dob, child_name)
values (6, to_date('30-01-2019', 'dd-mm-yyyy'), 'Olivia Miller');
insert into CHILD (child_id, child_dob, child_name)
values (7, to_date('14-07-2017', 'dd-mm-yyyy'), 'James Moore');
insert into CHILD (child_id, child_dob, child_name)
values (8, to_date('22-03-2018', 'dd-mm-yyyy'), 'Sophia Taylor');
insert into CHILD (child_id, child_dob, child_name)
values (9, to_date('12-05-2016', 'dd-mm-yyyy'), 'William Anderson');
insert into CHILD (child_id, child_dob, child_name)
values (10, to_date('28-02-2015', 'dd-mm-yyyy'), 'Isabella Thomas');
insert into CHILD (child_id, child_dob, child_name)
values (11, to_date('18-10-2014', 'dd-mm-yyyy'), 'Lucas Jackson');
insert into CHILD (child_id, child_dob, child_name)
values (12, to_date('01-04-2019', 'dd-mm-yyyy'), 'Mia White');
insert into CHILD (child_id, child_dob, child_name)
values (13, to_date('11-11-2017', 'dd-mm-yyyy'), 'Benjamin Harris');
insert into CHILD (child_id, child_dob, child_name)
values (14, to_date('09-06-2018', 'dd-mm-yyyy'), 'Charlotte Martin');
insert into CHILD (child_id, child_dob, child_name)
values (15, to_date('21-09-2016', 'dd-mm-yyyy'), 'Henry Thompson');
insert into CHILD (child_id, child_dob, child_name)
values (16, to_date('16-08-2015', 'dd-mm-yyyy'), 'Amelia Garcia');
insert into CHILD (child_id, child_dob, child_name)
values (17, to_date('27-07-2014', 'dd-mm-yyyy'), 'Alexander Martinez');
insert into CHILD (child_id, child_dob, child_name)
values (18, to_date('13-05-2019', 'dd-mm-yyyy'), 'Ava Robinson');
insert into CHILD (child_id, child_dob, child_name)
values (19, to_date('05-12-2017', 'dd-mm-yyyy'), 'Ethan Clark');
insert into CHILD (child_id, child_dob, child_name)
values (20, to_date('14-02-2018', 'dd-mm-yyyy'), 'Harper Rodriguez');
insert into CHILD (child_id, child_dob, child_name)
values (21, to_date('06-03-2016', 'dd-mm-yyyy'), 'Mason Lewis');
insert into CHILD (child_id, child_dob, child_name)
values (22, to_date('30-10-2015', 'dd-mm-yyyy'), 'Evelyn Lee');
insert into CHILD (child_id, child_dob, child_name)
values (23, to_date('10-01-2014', 'dd-mm-yyyy'), 'Logan Walker');
insert into CHILD (child_id, child_dob, child_name)
values (24, to_date('18-08-2019', 'dd-mm-yyyy'), 'Abigail Hall');
insert into CHILD (child_id, child_dob, child_name)
values (25, to_date('23-03-2017', 'dd-mm-yyyy'), 'Aiden Allen');
insert into CHILD (child_id, child_dob, child_name)
values (26, to_date('22-11-2018', 'dd-mm-yyyy'), 'Ella Young');
insert into CHILD (child_id, child_dob, child_name)
values (27, to_date('11-02-2016', 'dd-mm-yyyy'), 'Daniel Hernandez');
insert into CHILD (child_id, child_dob, child_name)
values (28, to_date('12-12-2015', 'dd-mm-yyyy'), 'Lily King');
insert into CHILD (child_id, child_dob, child_name)
values (29, to_date('07-06-2014', 'dd-mm-yyyy'), 'Jackson Wright');
insert into CHILD (child_id, child_dob, child_name)
values (30, to_date('19-03-2019', 'dd-mm-yyyy'), 'Grace Lopez');
insert into CHILD (child_id, child_dob, child_name)
values (31, to_date('09-09-2017', 'dd-mm-yyyy'), 'Sebastian Hill');
insert into CHILD (child_id, child_dob, child_name)
values (32, to_date('25-05-2018', 'dd-mm-yyyy'), 'Aria Scott');
insert into CHILD (child_id, child_dob, child_name)
values (33, to_date('03-07-2016', 'dd-mm-yyyy'), 'Jack Green');
insert into CHILD (child_id, child_dob, child_name)
values (34, to_date('19-04-2015', 'dd-mm-yyyy'), 'Zoe Adams');
insert into CHILD (child_id, child_dob, child_name)
values (35, to_date('17-02-2014', 'dd-mm-yyyy'), 'Owen Baker');
insert into CHILD (child_id, child_dob, child_name)
values (36, to_date('26-09-2019', 'dd-mm-yyyy'), 'Scarlett Gonzalez');
insert into CHILD (child_id, child_dob, child_name)
values (37, to_date('14-04-2017', 'dd-mm-yyyy'), 'Jacob Nelson');
insert into CHILD (child_id, child_dob, child_name)
values (38, to_date('30-08-2018', 'dd-mm-yyyy'), 'Victoria Carter');
insert into CHILD (child_id, child_dob, child_name)
values (39, to_date('21-10-2016', 'dd-mm-yyyy'), 'Gabriel Mitchell');
insert into CHILD (child_id, child_dob, child_name)
values (40, to_date('07-03-2015', 'dd-mm-yyyy'), 'Hannah Perez');
insert into CHILD (child_id, child_dob, child_name)
values (41, to_date('11-05-2014', 'dd-mm-yyyy'), 'Samuel Roberts');
insert into CHILD (child_id, child_dob, child_name)
values (42, to_date('03-11-2019', 'dd-mm-yyyy'), 'Layla Turner');
insert into CHILD (child_id, child_dob, child_name)
values (43, to_date('02-06-2017', 'dd-mm-yyyy'), 'Anthony Phillips');
insert into CHILD (child_id, child_dob, child_name)
values (44, to_date('12-10-2018', 'dd-mm-yyyy'), 'Sofia Campbell');
insert into CHILD (child_id, child_dob, child_name)
values (45, to_date('08-01-2016', 'dd-mm-yyyy'), 'Cameron Parker');
insert into CHILD (child_id, child_dob, child_name)
values (46, to_date('20-11-2015', 'dd-mm-yyyy'), 'Ella Evans');
insert into CHILD (child_id, child_dob, child_name)
values (47, to_date('02-09-2014', 'dd-mm-yyyy'), 'Matthew Edwards');
insert into CHILD (child_id, child_dob, child_name)
values (48, to_date('15-07-2019', 'dd-mm-yyyy'), 'Avery Collins');
insert into CHILD (child_id, child_dob, child_name)
values (49, to_date('16-01-2017', 'dd-mm-yyyy'), 'Nathan Stewart');
insert into CHILD (child_id, child_dob, child_name)
values (50, to_date('28-12-2018', 'dd-mm-yyyy'), 'Madison Sanchez');
insert into CHILD (child_id, child_dob, child_name)
values (51, to_date('12-05-2018', 'dd-mm-yyyy'), 'Liam Johnson');
insert into CHILD (child_id, child_dob, child_name)
values (52, to_date('23-08-2017', 'dd-mm-yyyy'), 'Emma Martinez');
insert into CHILD (child_id, child_dob, child_name)
values (53, to_date('05-11-2016', 'dd-mm-yyyy'), 'Noah Rodriguez');
insert into CHILD (child_id, child_dob, child_name)
values (54, to_date('17-09-2015', 'dd-mm-yyyy'), 'Olivia Smith');
insert into CHILD (child_id, child_dob, child_name)
values (55, to_date('30-11-2014', 'dd-mm-yyyy'), 'Lucas Brown');
insert into CHILD (child_id, child_dob, child_name)
values (56, to_date('10-02-2019', 'dd-mm-yyyy'), 'Ava Davis');
insert into CHILD (child_id, child_dob, child_name)
values (57, to_date('07-07-2017', 'dd-mm-yyyy'), 'Mia Wilson');
insert into CHILD (child_id, child_dob, child_name)
values (58, to_date('18-03-2018', 'dd-mm-yyyy'), 'Liam Thomas');
insert into CHILD (child_id, child_dob, child_name)
values (59, to_date('09-05-2016', 'dd-mm-yyyy'), 'Ethan White');
insert into CHILD (child_id, child_dob, child_name)
values (60, to_date('25-02-2015', 'dd-mm-yyyy'), 'Sophia Lee');
insert into CHILD (child_id, child_dob, child_name)
values (61, to_date('03-11-2014', 'dd-mm-yyyy'), 'Mason Taylor');
insert into CHILD (child_id, child_dob, child_name)
values (62, to_date('28-03-2019', 'dd-mm-yyyy'), 'Amelia Harris');
insert into CHILD (child_id, child_dob, child_name)
values (63, to_date('16-11-2017', 'dd-mm-yyyy'), 'Michael Clark');
insert into CHILD (child_id, child_dob, child_name)
values (64, to_date('14-06-2018', 'dd-mm-yyyy'), 'Alexis King');
insert into CHILD (child_id, child_dob, child_name)
values (65, to_date('19-09-2016', 'dd-mm-yyyy'), 'Elijah Moore');
insert into CHILD (child_id, child_dob, child_name)
values (66, to_date('20-08-2015', 'dd-mm-yyyy'), 'Harper Jackson');
insert into CHILD (child_id, child_dob, child_name)
values (67, to_date('25-07-2014', 'dd-mm-yyyy'), 'Logan Hall');
insert into CHILD (child_id, child_dob, child_name)
values (68, to_date('03-05-2019', 'dd-mm-yyyy'), 'Isabella Nelson');
insert into CHILD (child_id, child_dob, child_name)
values (69, to_date('15-12-2017', 'dd-mm-yyyy'), 'Aiden Young');
insert into CHILD (child_id, child_dob, child_name)
values (70, to_date('01-02-2018', 'dd-mm-yyyy'), 'Ellie Garcia');
insert into CHILD (child_id, child_dob, child_name)
values (71, to_date('02-03-2016', 'dd-mm-yyyy'), 'James Perez');
insert into CHILD (child_id, child_dob, child_name)
values (72, to_date('13-10-2015', 'dd-mm-yyyy'), 'Charlotte Adams');
insert into CHILD (child_id, child_dob, child_name)
values (73, to_date('22-01-2014', 'dd-mm-yyyy'), 'Benjamin Turner');
insert into CHILD (child_id, child_dob, child_name)
values (74, to_date('28-08-2019', 'dd-mm-yyyy'), 'Mila Phillips');
insert into CHILD (child_id, child_dob, child_name)
values (75, to_date('11-04-2017', 'dd-mm-yyyy'), 'Owen Evans');
insert into CHILD (child_id, child_dob, child_name)
values (76, to_date('21-11-2018', 'dd-mm-yyyy'), 'Emily Miller');
insert into CHILD (child_id, child_dob, child_name)
values (77, to_date('12-02-2016', 'dd-mm-yyyy'), 'Lucas Campbell');
insert into CHILD (child_id, child_dob, child_name)
values (78, to_date('05-12-2015', 'dd-mm-yyyy'), 'Abigail Martinez');
insert into CHILD (child_id, child_dob, child_name)
values (79, to_date('10-06-2014', 'dd-mm-yyyy'), 'William Sanchez');
insert into CHILD (child_id, child_dob, child_name)
values (80, to_date('20-03-2019', 'dd-mm-yyyy'), 'Madison Hall');
insert into CHILD (child_id, child_dob, child_name)
values (81, to_date('29-09-2017', 'dd-mm-yyyy'), 'Lincoln Baker');
insert into CHILD (child_id, child_dob, child_name)
values (82, to_date('05-05-2018', 'dd-mm-yyyy'), 'Evelyn Collins');
insert into CHILD (child_id, child_dob, child_name)
values (83, to_date('07-07-2016', 'dd-mm-yyyy'), 'Mila Thompson');
insert into CHILD (child_id, child_dob, child_name)
values (84, to_date('09-04-2015', 'dd-mm-yyyy'), 'Henry Wright');
insert into CHILD (child_id, child_dob, child_name)
values (85, to_date('21-02-2014', 'dd-mm-yyyy'), 'Grace Robinson');
insert into CHILD (child_id, child_dob, child_name)
values (86, to_date('26-09-2019', 'dd-mm-yyyy'), 'Sebastian Stewart');
insert into CHILD (child_id, child_dob, child_name)
values (87, to_date('04-04-2017', 'dd-mm-yyyy'), 'Aria Perez');
insert into CHILD (child_id, child_dob, child_name)
values (88, to_date('11-08-2018', 'dd-mm-yyyy'), 'John Garcia');
insert into CHILD (child_id, child_dob, child_name)
values (89, to_date('18-10-2016', 'dd-mm-yyyy'), 'Elizabeth Allen');
insert into CHILD (child_id, child_dob, child_name)
values (90, to_date('27-03-2015', 'dd-mm-yyyy'), 'Nathan Thomas');
insert into CHILD (child_id, child_dob, child_name)
values (91, to_date('01-05-2014', 'dd-mm-yyyy'), 'Lily Adams');
insert into CHILD (child_id, child_dob, child_name)
values (92, to_date('02-11-2019', 'dd-mm-yyyy'), 'Landon Hernandez');
insert into CHILD (child_id, child_dob, child_name)
values (93, to_date('03-06-2017', 'dd-mm-yyyy'), 'Zoe Scott');
insert into CHILD (child_id, child_dob, child_name)
values (94, to_date('22-10-2018', 'dd-mm-yyyy'), 'Ella Rodriguez');
insert into CHILD (child_id, child_dob, child_name)
values (95, to_date('10-01-2016', 'dd-mm-yyyy'), 'Lincoln Lee');
insert into CHILD (child_id, child_dob, child_name)
values (96, to_date('12-11-2015', 'dd-mm-yyyy'), 'Aurora Turner');
insert into CHILD (child_id, child_dob, child_name)
values (97, to_date('01-09-2014', 'dd-mm-yyyy'), 'Adam Harris');
insert into CHILD (child_id, child_dob, child_name)
values (98, to_date('16-07-2019', 'dd-mm-yyyy'), 'Leah Parker');
insert into CHILD (child_id, child_dob, child_name)
values (99, to_date('27-01-2017', 'dd-mm-yyyy'), 'Hudson Perez');
insert into CHILD (child_id, child_dob, child_name)
values (100, to_date('18-12-2018', 'dd-mm-yyyy'), 'Skylar Martinez');
